### ISSUE TITLE
Custom HTTP Methods

### ISSUE THREAD

**Issue by jaredhanks** [postmanlabs/postman-app-support#958] opened 2015-03-09 22:08 UTC
Any chance of adding the ability for custom HTTP Methods?  I need the ability to use "QUEUE" as a method.

**Comment by francescotonini** [comment] 2016-02-06 13:48
It has been almost a year, any changes? :)

**Comment by a85** [comment] 2016-06-19 18:34
Closing this as duplicate of #166. The new Postman Runtime based on Node.js will solve this: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

**Closed by a85** 2016-06-19 18:34 UTC
Labels: Feature
