### ISSUE TITLE
create subfolders in a collection

### ISSUE THREAD

**Issue by yehosef** [postmanlabs/postman-app-support#907] opened 2015-02-05 09:53 UTC
We have several APIs we're working with, each have many many resources and endpoints.

Generally how I would like to organize it is by resource, but sometimes the resource I'm getting is actually a part of another resource - example:
POST /comments
GET /comments
GET /comments/<id>
GET /comments/<id>/likes
DELETE /comments/<id>/likes
PUT /comments/<id>/likes

then I have 
GET /member/<id>/comments
GET /member/<id>/comments/likes
GET /post/<id>/comments
GET /post/<id>/comments/likes

etc.  This is just a simple example, - but it can go on and get more complicated.

It would be great if I could make a folder under [comments] so I could also have a [comments][member] and a [comments][post]  etc.

I think for now adding another level would be sufficient.. I can understand how adding infinite levels would be difficult to support and probably not so in demand.  If you wanted to be able support infinite levels, you might think about a UX similar to workflowy where you can "zoom" in - where the next level in becomes the top level and there are bread crumbs at the top to see where you are. - this would be amazing.

**Comment by sunshineo** [comment] 2015-03-23 21:41
1 level folder is supported, this should be closed.
But really need multiple level of folders / nested folders.

**Comment by yehosef** [comment] 2015-03-24 08:38
I'm specifically asking for more than one level, how is it that this should be closed?

![postman_and_create_subfolders_in_a_collection_ _issue__907_ _a85_postman-chrome-extension](https://cloud.githubusercontent.com/assets/149253/6798028/db10fa04-d211-11e4-89e2-1cdd7a309f92.png)

**Comment by sunshineo** [comment] 2015-03-24 17:10
@yehosef I read it wrong but you are not good at wording things either. You should have "multiple" or "nested" or something like that in the title or the body. The picture should help.

**Comment by yehosef** [comment] 2015-03-25 07:41
@sunshineo - I'm sorry you're not good at reading english - it's a tricky language ;).  Since in a collection you can already create "folders", I'm asking for "subfolders" - which is an additional feature.  I'm glad you understand better now. 

![image](https://cloud.githubusercontent.com/assets/149253/6820004/ffd7b97e-d2d2-11e4-8bfb-f10b9a06f866.png)

**Comment by sunshineo** [comment] 2015-03-26 07:17
@yehosef Well, keep the pretty pictures coming. With the crappy title you picked from your crappy vocabulary. No one is going to look at it.

**Comment by yehosef** [comment] 2015-03-26 08:59
Now for something constructive.

@a85 - the more I use this with multiple collections, the more I think having a "zoomed" view would be really helpful (think workflowy).

I think of a collection representing a particular API (eg, twitter, github, etc).  I want to mention two things: 

1) When I'm working on a particular API, it's not common that I also need easy access to other collections/API.  If I did my preference would be to handle this in multiple windows (if chrome apps support it) or tabs.  

2) it's common for the APIs to be very big and complex (see https://developer.github.com/v3/) and the current structure becomes unwieldy with such a size.  It seems the main issues are UX. You could make it so you can even expand a single collection from the main collection list and to see a collection you click on it to "zoom in" to a single collection view. The single collection view would use the two visual levels that are currently visible to represent the folders,  subfolders and endpoints.  the only (subtle) difference is that you cannot current put an endpoint at the "global" scope, which in my suggested approach would be the root of the collection.

I'm curious if you've heard similar feedback from other users or heard how they handle multiple big APIs/collections.  Maybe there is some other approaches or hacks that would work for me.

Thanks

**Comment by kevinjalbert** [comment] 2015-03-31 20:09
+1

**Comment by collinpeters** [comment] 2015-03-31 20:44
+1

**Comment by youranwj** [comment] 2015-04-01 22:09
+1

**Comment by deepredsky** [comment] 2015-04-17 15:27
+1

**Comment by MarkMurphy** [comment] 2015-04-20 13:45
+1 I agree, I have multiple apis and need to nest folders at least one level deeper

**Comment by eappell** [comment] 2015-05-13 15:55
+1

**Comment by ppolyzos** [comment] 2015-07-29 21:17
+1

**Comment by stramel** [comment] 2016-01-22 15:34
:+1:

**Comment by superruzafa** [comment] 2016-02-02 11:38
+1

**Comment by defaultbob** [comment] 2016-03-01 13:41
+1

**Comment by igostavro** [comment] 2016-03-14 14:31
+1

**Comment by gioid** [comment] 2016-03-16 14:23
+1

**Comment by yargevad** [comment] 2016-03-16 19:38
+1, subfolder support would be great

**Comment by jamesaspence** [comment] 2016-05-26 19:10
+1. I very much want collections with folders, with subfolders inside the folders, etc. etc.

**Comment by aelgali** [comment] 2016-06-03 13:18
+1

**Comment by mpurdon** [comment] 2016-06-13 15:44
+1

**Comment by zappen999** [comment] 2016-06-16 11:54
+1

**Comment by adamtickner** [comment] 2016-07-04 05:01
+1

**Comment by makison** [comment] 2016-07-04 10:43
+1

**Comment by dmitry-fedoseev** [comment] 2016-07-06 14:14
+1

**Comment by monkpit** [comment] 2016-08-02 18:57
So how many years does it take to get a response?

**Comment by a85** [comment] 2016-08-04 19:56
This is on our immediate roadmap now. We needed to do several things to make this possible. Subfolder support requires changes in the following:
1. Data format for collections
2. Collection runner (How Postman executes collections)
3. Internal data store and syncing
4. Postman UI

We just pushed an update 4.5 on the Mac app that has the new Postman Runtime which takes care of 1 and 2. We are working hard on 3 and 4 now.

**Comment by beetlerom** [comment] 2016-08-15 11:33
Just wondering if there is an ETA on this on. I am planning to start a new project and would like to know if I can rely on the new structure possibilities for it. 

Thank you!

**Comment by koleror** [comment] 2016-08-17 12:59
+1

**Comment by ondrejkrpec** [comment] 2016-08-24 08:21
+1

**Comment by ghost** [comment] 2016-09-14 05:14
+1

**Comment by hkgill** [comment] 2016-09-15 05:32
+1

**Comment by mchambaud** [comment] 2016-09-23 14:25
+1

**Comment by fredbouchard** [comment] 2016-09-23 14:46
+1

**Comment by victor-ponamariov** [comment] 2016-09-30 13:34
+1

**Comment by DeividasJackus** [comment] 2016-10-03 13:26
+1

**Comment by rammrain** [comment] 2016-10-05 09:45
+1

**Comment by SeanStewart37** [comment] 2016-10-06 13:33
+1

**Comment by rafael-iop** [comment] 2016-10-08 20:56
+1

**Comment by bgarrison25** [comment] 2016-10-12 15:05
+1

**Comment by phoenixgao** [comment] 2016-10-13 03:38
+1 Any estimate?

**Comment by stwist-timeless** [comment] 2016-10-13 12:15
+1

**Comment by Kalzem** [comment] 2016-10-13 12:56
+1

**Comment by lthurston** [comment] 2016-10-14 21:17
+1

**Comment by monkpit** [comment] 2016-10-14 23:18
Enough "+1"s - you can use the github reaction feature to add a thumbs up, etc to any post without triggering emails to everyone that contain only the text "+1" and lack actual content.

Thanks!

**Comment by doncadavona** [comment] 2016-12-14 04:24
+1

**Comment by stramel** [comment] 2016-12-14 23:43
+1 to @monkpit's comment

**Comment by kamiwa** [comment] 2017-01-08 15:49
+1

**Comment by GMolini** [comment] 2017-01-09 11:26
+1

**Comment by corbfon** [comment] 2017-01-12 00:12
+1

**Comment by sdnts** [comment] 2017-01-12 07:34
Guys, we're working on support for multi-level folders. Will keep you all updated here :)

**Comment by eprice-rw** [comment] 2017-02-23 13:45
+1

**Comment by cesarbmx** [comment] 2017-02-27 10:35
+1, although one level is ok. I just want the resources properly grouped:
- comments
- comments likes
- ...

**Comment by nedkoh** [comment] 2017-03-07 17:46
+1 sounds like the insanity keeps going on. We're evaluating moving away from using Postman due to some of its limitations including organization and ACLs.

**Comment by Martyrer** [comment] 2017-03-16 11:07
+1

**Comment by psyfear** [comment] 2017-03-31 03:26
+1

**Comment by wilcorrea** [comment] 2017-04-02 22:04
+1 pleeassseeee

**Comment by a85** [comment] 2017-04-03 20:11
We have an internal build for multi-level folders that we are testing out. Tons of moving parts especially around the data model. Thank you everyone for your patience. We are trying our best and hope to put this out soon.

**Comment by sp71** [comment] 2017-04-12 17:51
+1

**Comment by csegyud** [comment] 2017-04-13 09:10
Just updated and works great! BTW, do you plan in the future to further nesting folders into folders instead of "just" one level of folders in a collection? Thanks for the new feature!

**Comment by nicolasdalsass** [comment] 2017-04-13 15:56
I don't understand why this is closed.

I just updated to the latest available Postman (4.10.7) on Ubuntu, and I don't think it contains this feature ?

Could you give use more info about the release status ?

**Comment by jamesaspence** [comment] 2017-04-13 16:29
@nicolasdalsass I believe you are mistaken. This issue is still open?

**Comment by igostavro** [comment] 2017-04-13 23:44
this issue should still be open. There are no nested folders. 
On OS X with the latest version, the feature is not present. Would be immensely helpful.

**Comment by a85** [comment] 2017-04-13 23:47
@igostavro This issue is NOT closed. The issue that is closed is a duplicate of the same issue. There are multiple duplicate issues filed on the tracker and we close duplicates from time to time.

**Comment by igostavro** [comment] 2017-04-13 23:49
@a85 excellent

**Comment by rapidroamer** [comment] 2017-04-18 00:20
+1

**Comment by GWJYonder** [comment] 2017-04-21 14:13
Not sure if this is too late, since it looks like this issue is (hopefully) already past its 11th hour, but it would be great if we could re-order the folders and sub-folders manually. Right now the HTTP Requests can be dragged around at will, but the folders are locked alpha-numeric. We are currently prepending numbers to the folders to enforce our own ordering, but as you can imagine that makes changing the order quite annoying.

**Comment by luiscavero** [comment] 2017-04-26 12:06
@a85 Thanks, I can't find this in the Postman Roadmap Trello, is that feature a near term?

**Comment by a85** [comment] 2017-04-26 23:53
@luiscavero It's under the title of Multi-Level folders: https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers

**Comment by Heydiddly** [comment] 2017-04-27 08:57
@a85 Thanks, I for one wasn't aware of that roadmap - great to see that this and the folder re-ordering mentioned above are both targetted for near-term release.

**Comment by luiscavero** [comment] 2017-05-29 12:19
Hello @a85 , last week you posted an entry saying that the multilevel folders feature would be ready during that week. 
However, there is still no new release (or I did not get it). Also, I received the May 2017 Postman Newsletter and this feature is not listed. 

I do not like being boring but ... when will that be ready to start creating multilevel collections?

Thank you!

**Comment by sdnts** [comment] 2017-05-29 13:05
Hi @luiscavero, Multi-level folders are up on our Canary channel:

This is undergoing heavy testing right now to make sure it plays well with everything else. We'd love your feedback as well, so if you find any issues, please create issues on this repo :)

You can download the canary build here:

OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by stefanthorpe** [comment] 2017-06-06 10:00
@madebysid I've found a couple of bugs with the Canary deploys mostly around sync and resync issues. However, the most annoying one being that one of my environments had all its variables removed.

Update: On further testing ```pm.environment.clear("variableName")``` is deleteing everything. This is a prebuilt code snippet that replaces ```postman.clearEnvironmentVariable("token")```.

Although I haven't extensively tested yet I believe the same is true of ```pm.globals.clear("value");```

**Comment by Techcadia** [comment] 2017-06-14 00:48
Disappointed to see this not in the 5.0.0 release. Do you guys have an ETA on this

**Comment by lukik** [comment] 2017-06-20 01:14
+1 
.... patiently waiting for this.

**Comment by a85** [comment] 2017-07-19 20:42
The feature is out in 5.1! Get it here: www.getpostman.com/apps

**Closed by a85** 2017-07-19 20:42 UTC
Labels: Feature, Usability

**Comment by yehosef** [comment] 2017-07-20 13:51
great! - but I went to the page and don't see 5.1 - am I missing something?

**Comment by Techcadia** [comment] 2017-07-20 16:12
The Canary build fails to export the  json files with correct foldering and "_postman_isSubFolder": true. But the Actual current 5.1 works fine. Figured I might mention it here.

**Comment by SamvelRaja** [comment] 2017-07-20 16:50
@yehosef we released only for native application at present. 
And 
@Techcadia thanks for bringing this to our notice we shall take a look at that 👍🏻

**Comment by yehosef** [comment] 2017-07-20 17:04
ok - I was looking at the page after the github issue was closed - but the
site wasn't updated yet.  Now the site is updated.

**Comment by KeynesYouDigIt** [comment] 2017-07-21 18:32
What happened to this feature? When I go to get the linux native app v5.1, v5.0 downloads again and I loose nested folders, which messes us up a bit

**Comment by KeynesYouDigIt** [comment] 2017-07-21 18:33
Can someone link me to 5.1 or was it broken in someway?
