### ISSUE TITLE
Extremely slow with large responses

### ISSUE THREAD

**Issue by ilanbiala** [postmanlabs/postman-app-support#793] opened 2014-11-07 15:02 UTC
I have a GET that requests about 3000 rows from a DB and almost completely crashes Postman. Can it be optimized to handle larger requests?

**Comment by dandv** [comment] 2015-01-06 02:19
Is this a duplicate of #767?

I experience the same problem - with large requests (100k lines, 1.5Mb), Postman (Packaged App) almost freezes. (The non-packaged app would regularly be killed by Chrome.)

[DHC](https://chrome.google.com/webstore/detail/dhc-resthttp-api-client/aejoelaoggembcahagimdiliamlcdmfm) has no problem dealing with the same request.

**Comment by ilanbiala** [comment] 2015-01-06 02:28
@dandv that one refers to a request that takes a long time. I am talking about a quick, but large (data-heavy) request.

**Comment by sdnts** [comment] 2016-11-23 09:29
Is this still an issue on the latest native apps? (4.8.3)

**Comment by ilanbiala** [comment] 2016-11-26 21:58
@madebysid I don't have access to the data anymore, but you can try it out by just doing a request for all the records in a table and just keep adding to the table until you notice the slowdown.

**Comment by puviyarasan** [comment] 2017-05-24 21:22
We see that Postman completely hangs/ does not respond, when the response has a large body. Is there a way to turn off body processing / not show the body?

**Comment by OneCrazyRussian** [comment] 2017-11-16 12:30
This is still an issue on both request bodies and request results in the native app, not only high CPU usage (100% on single core) but also high HDD throughput on every request change (mostly writing into IndexedDB .log files, why even do that while I'm editing the request?), this completely kills my perfomance and does not allow to test services with large request support (up to 100mb)

Moreover the lags and high RAM usage continue in background even if I don't edit the large request body. And by large I mean 2m are tolerable at most, 5mb and more are just completely unusable.

**Comment by AxelDalenAndersenP** [comment] 2018-01-22 14:51
Yes, still an issue.
I have time right now to type this while waiting for Postman to switch tab...

**Comment by xchopin** [comment] 2018-04-16 09:42
Problem appears after the new update.

- Version: 6.0.10
- OS: macOS High Sierra
- Size of the response: 19.53MB
- Time of the response: 5896ms
- Description: 
     _First of all it looks like it takes more time to load documents_. After loading : 
    * If PostMan was in a window and then I enable the full screen on Mac I get a GUI issue (it doesn't resize the client: it just adds a grey background (dark mode).
    * It's very laggy when I switch between tabs (I have to close the tab to make it faster)

**Comment by numaanashraf** [comment] 2018-06-29 11:48
@xchopin @AxelAndersen @OneCrazyRussian @puviyarasan @ilanbiala @dandv @james-m-henderson We have created a master thread #4751 to track all issues related to large responses. We would be updating that thread on possible workarounds, planned improvements and releases related to large response performance.

**Closed by numaanashraf** 2018-06-29 11:48 UTC
Labels: Bug, Performance
