### ISSUE TITLE
pretty viewer for JSON response doesn't decode escape characters

### ISSUE THREAD

**Issue by farin** [postmanlabs/postman-app-support#924] opened 2015-02-18 13:48 UTC
Eg. raw json
{"links":[{"href":"http:\/\/localhost:5000\/api_1_0\/images","rel":"self"}]}

in pretty print, html link still contains escaping backslashes instead real text value
(according to json spec forward slashes can be escaped but it's not mandatory. Some libraries, like python ujson, produce jsons with such escape characters)

**Comment by ivan-novakov** [comment] 2015-03-04 06:09
+1

It would be nice to have the option to "switch on/off" URL slash escaping.

**Comment by bazted** [comment] 2015-03-28 13:23
The most strange thing is that in Postman - REST Client(not packaged app) URL is parsed correctly and can be even clicked. It is strange that packaged app has this bug.

**Comment by cameron-fgx** [comment] 2015-04-01 09:42
+1

The issue isn't only on the "pretty" viewer, raw and preview are also escaped.

**Comment by kevinvanmierlo** [comment] 2015-07-03 12:39
+1

This is a thing that really bugs me

**Comment by cnanney** [comment] 2015-07-07 20:43
Yeah, "raw" is not really raw when displaying `"Token":"oe0/18uk"` as `"Token":"oe0\/18uk"`

**Comment by abhijitkane** [comment] 2015-07-07 20:48
@cameron-fgx @cnanney What version of Postman are you on?

In 3.0.2, a server response of `{"Token":"oe0/18uk"}` is rendered as-is in the raw view and preview.

**Comment by cnanney** [comment] 2015-07-07 21:11
My mistake, this is not a Postman problem. Apparently the API is escaping forward slashes in the JSON response, so the actual value of `oe0/18uk` is being returned and displayed as `oe0\/18uk` in Postman raw and preview tab, and `oe0\\/18uk` in pretty.

When I use the "copy response" button from from any view, the escaping is removed and `oe0/18uk` is in my clipboard.

Is there a way for Postman to detect the escaped slashes and display it properly in the pretty tab? Raw should be the actual raw response, but in pretty can it unescape the slashes?

**Comment by cnanney** [comment] 2015-07-23 17:02
This is now worse in 3.0.5.

A response of `{"Token":"oe0\/18uk"}` is still displayed in all views as `{"Token":"oe0\\/18uk"}`, but is also now copying response to clipboard as `{"Token":"oe0\\/18uk"}`, where before it smartly removed all escaping nonsense and copied `{"Token":"oe0/18uk"}` to clipboard.

I think in Pretty and Preview view, it should properly unescape all these entities, so `a\/e` displays as `a/e`. Raw should always show the raw response. Same for copying to clipboard... If you copy from pretty/preview, it copies with the decoded escape characters, but raw copies the raw response.

**Comment by abhijitkane** [comment] 2015-12-29 18:48
@cnanney Can you confirm this fixed in 3.2.8 of the app?

**Comment by cnanney** [comment] 2015-12-29 19:34
In 3.2.8 (packaged), this is resolved. I do notice that the "copy response to clipboard" button always produces the same output, rather than copying the raw response if you are viewing the raw tab when you press the button.

This is no big deal, because if you want the actual raw data, you can always just manually copy and paste it from the textarea.

**Closed** 2016-03-30 09:53 UTC
Labels: Bug, Tentative
