### ISSUE TITLE
Feature Request: Say what part of OAuth flow went wrong

### ISSUE THREAD

**Issue by navarr** [postmanlabs/postman-app-support#633] opened 2014-07-10 17:54 UTC
I use POSTMAN to run by-hand requests against my server to make sure my API is returning the right stuff.  Of course, I'm implementing an OAuth API and while an implicit user-credential endpoint exists, I'm trying to setup a non-credential implicit (prompts the user to allow).

So I'm trying to use Postman to figure out where things are going wrong and set it up, but postman only says "OAuth2 Flow Failed"  That's not very helpful, as I don't know what it expects and what's failing.

So any sort of additional information attached to that message would be great for helping debug OAuth2 implementations!

**Comment by neverendingqs** [comment] 2017-03-17 21:38
@navarr - as a workaround, you can navigate to `chrome://inspect/#apps` in chrome, and inspect either the main Postman window or the pop-up when doing the authorization grant flow.

**Comment by giridharvc7** [comment] 2022-12-13 07:46
This is a duplicate of #10124, we are tracking it there.

**Closed by giridharvc7** 2022-12-13 07:46 UTC
Labels: bug, Auth, user-interface, product/runtime
