### ISSUE TITLE
folder in folder support

### ISSUE THREAD

**Issue by dn2k-dev** [postmanlabs/postman-app-support#804] opened 2014-11-12 08:06 UTC
Hi,

Does it possible to add folder in folder support? 
We updating a huge collection with more than 150 APIs and currently we have 40 folders.
It will be better to arrange it in folders structure.

**Comment by sunshineo** [comment] 2015-03-23 21:36
+1

**Comment by kevinjalbert** [comment] 2015-03-31 20:06
+1

**Comment by kajo123** [comment] 2015-07-09 08:33
+1

**Comment by josephnoall** [comment] 2015-07-23 16:02
+1

**Comment by srbangre** [comment] 2016-01-21 18:51
+1

**Comment by rick-nu** [comment] 2016-04-18 12:21
+1

**Comment by seslav** [comment] 2017-05-30 11:22
+1

**Comment by a85** [comment] 2017-06-27 21:45
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/907. This is coming to Postman soon within a few weeks.

**Closed by a85** 2017-06-27 21:45 UTC
Labels: collection-v2, Feature

**Comment by rick-nu** [comment] 2017-06-28 08:56
![](https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif)
