### ISSUE TITLE
Option to send GET request body

### ISSUE THREAD

**Issue by alecplumb** [postmanlabs/postman-app-support#131] opened 2012-10-17 21:40 UTC
It would be nice to be able to send a body with a GET request. I understand that this may not be considered a good practice, but this is necessary for the API that I have to work with.

**Comment by calexandre** [comment] 2015-01-28 15:12
+1 for this feature.

I also have an API that uses GET with Body. The main reason is that my query is very complex, and therefore is encapsulated within a json object that is sent in the BODY. Modifying it to a POST/PUT would not make any sense because I'm not issuing changes against any resource.

Also, I have not found anything in the HTTP specification constraining the use of a BODY within a GET request.

**Comment by ksilin** [comment] 2015-02-28 19:46
+1

**Comment by amineck** [comment] 2015-04-10 16:05
+1

**Comment by nlundquist** [comment] 2015-04-23 20:09
+1

**Comment by Youmoo** [comment] 2015-05-03 07:11
+1. 
Elasticsearch query dsl needs get with request body.

**Comment by jonyadamit** [comment] 2015-05-07 16:58
+1 for ElasticSearch

**Comment by mcescalante** [comment] 2015-05-14 19:04
+1 for Elastic, which can require very complex query parameters for searches (which use GET, as no resource is modified). Would be awesome to be able to put this stuff in prettified.

**Comment by zlosim** [comment] 2015-05-18 12:14
+1 for Elastic

**Comment by jbratu** [comment] 2015-05-22 19:03
As Pooshen indicated, simply use POST instead of GET and it will work. Elasticsearch will accept a POST search even though nothing is being modified.

This issue can be closed because the HTTP specification for the GET verb doesn't support a body.

**Comment by kazhuravlev** [comment] 2015-06-07 11:40
+1

**Comment by adalinesimonian** [comment] 2015-06-07 23:10
@congruityservice is right; I can say from having used current versions of Elasticsearch that _this feature is no longer a requirement_ as **you can send the same request that you would send with a GET with a POST instead and it will work identically**.

Now, to sort something out about the HTTP/1.1 specification:

RFC 2616, section 4.3 clearly states:

> A message-body **MUST NOT be included** in a request **if the specification of the request method** (section 5.1.1) **does not allow sending an entity-body** in requests.
> https://tools.ietf.org/html/rfc2616#section-4.3

_However_, in the entirety of [section 9.3](https://tools.ietf.org/html/rfc2616#section-9.3), the section defining the GET verb, **nothing prevents a GET request from having a body**.

But before you draw any conclusions - the functionality defined for the GET verb also **does not include any logic involving the message body**.

In other words, if we are to follow the specification:
1. **It is possible** to send a message body with a GET request per specification.
2. However, the server responding to the GET request **must ignore the body** to follow the standard.

Essentially, there is no point, per standard, to send a body with a GET request, even though it is not explicitly disallowed.

[Roy T. Fielding](http://roy.gbiv.com/) backs this interpretation up:

> ...**any HTTP request message is allowed to contain a message body**, and thus must parse messages with that in mind. **Server semantics for GET**, however, are restricted such that **a body**, if any, **has no semantic meaning to the request**. The requirements on parsing are separate from the requirements on method semantics.
> So, yes, **you can send a body with GET, and no, it is never useful to do so**.
> https://groups.yahoo.com/neo/groups/rest-discuss/conversations/messages/9962

Taking all of this into consideration, I believe this issue should be closed as adding this functionality should have no effect or use per standard. Elasticsearch, though a great product, should not dictate how the HTTP standard is to be or not to be enforced.

**Comment by Loopingo** [comment] 2015-06-15 16:33
+1 for JIRA ZEPHYR API
=> http://docs.getzephyr.apiary.io/#get-%2Fjira_server%2Frest%2Fzapi%2Flatest%2Futil%2FversionBoard-list

**Comment by yaraju** [comment] 2015-07-11 15:38
@vsimonian ElasticSearch "Scroll & scan" search queries still require GET.If you do a POST they give 0 hits.

I had to switch to CURL to test my "scroll & scan" searches, while I was using Postman for just about everything else that I test out on my ES backend through a proxy.

**Comment by amosshapira** [comment] 2015-07-17 10:25
RFC or no RFC - what's the argument against allowing GET with a body? I'm here for ElasticSearch too (paying postman customer BTW), and fail to see what's wrong with letting people use it.
ElasticSearch feels that it's nicer to enable GET with a body because it's supposed to be a query operation which doesn't change anything on the server, think SQL "SELECT" vs. "INSERT"/"UPDATE".

**Comment by abhijitkane** [comment] 2015-07-17 10:30
There's no restriction from Postman, but Chrome's XHR object does not include bodies for GET requests, even if you include it in xhr.send().

**Comment by amosshapira** [comment] 2015-07-17 10:35
Thanks for the clarification @abhijitkane, that would be a blocker...

**Comment by apatrida** [comment] 2015-08-27 13:52
A few comments above mention this from a REST viewpoint (no entity is being modified, don't want to use POST).  But...  I think you have to view the `/_search` endpoint of ElasticSearch not as REST, but a custom protocol they defined over HTTP for querying, and querying hasn't ever really been addressed in people talking about REST.  You have "GET a resource" in general REST ideals, but not "FIND a set of things as full or partial projections, aggregations or summarization of those things."   Therefore saying "I need GET with a body because a REST API I'm calling that does not modify a resource needs a big complex query string" doesn't fly.  You use POST because that is what their custom protocol allows when GET with query parameters fails.  Some of the ElasticSearch plugins (KOPF I think) return all results on a GET because they do not successfully pass the body from javaScript to the server on all browsers.  Not a good example to follow.

**Comment by nellochen** [comment] 2015-11-09 10:29
I got the answer!

**Comment by wangshuwei5** [comment] 2015-11-18 10:10
+1 for Elastic

**Comment by dominiksipowicz** [comment] 2015-12-02 17:01
+1

**Comment by Gabitchov** [comment] 2016-01-18 10:52
+1

**Comment by ghost** [comment] 2016-01-18 14:43
+1 for Elastic

**Comment by a85** [comment] 2016-01-18 17:12
For people posting about Elastic: You can replace GET with POST and ElasticSearch will work as expected. We are replacing the underlying networking stack in Postman so that we can have more control than XHR. This is still some time away.

**Comment by gregsdennis** [comment] 2016-02-25 15:57
+1 (can I do a +2, or maybe a +∞?)

Just to jump on the pile, [Trello's API](https://developers.trello.com/advanced-reference) does this because the parameter lists would be too long for URLs to support.

In regard to it being meaningless, I think that's really up to the API's developer, regardless of what the standard says the call _should_ do.

**Comment by andreagrandi** [comment] 2016-02-29 13:24
I understand this doesn't work with Chrome, but you also have an OSX native client. Why the feature is not available for the native client then? Thanks

**Comment by zgin** [comment] 2016-03-10 15:37
+1 elastic. Please.

**Comment by henry40408** [comment] 2016-03-14 08:10
+1 for ElasticSearch, please

**Comment by calfzhou** [comment] 2016-03-17 09:08
+1 for ElasticSearch

**Comment by rfyiamcool** [comment] 2016-03-29 03:09
+1 for Elastic   !

**Comment by mitchellgordon95** [comment] 2016-03-31 22:27
+1 elasticsearch

**Comment by a85** [comment] 2016-04-02 07:02
Reiterating: For people posting about Elastic: You can replace GET with POST and ElasticSearch will work as expected. We are replacing the underlying networking stack in Postman so that we can have more control than XHR. This is still some time away.

A new Node.js based networking stack will be available soon that will help us add bodies for GET calls.

**Closed by a85** 2016-04-02 07:02 UTC
Labels: Feature

**Comment by harryi3t** [comment] 2018-10-25 17:16
This is out on our [latest canary](https://www.getpostman.com/canary) channel and will be released with the next production version 6.5.0

**Comment by wajid23071dev** [comment] 2019-01-05 20:04
Postman does not allow you to add payload with Get request, however for Elastic search you can do that anyrequest tab in elasticsearch head plugin.

**Comment by harryi3t** [comment] 2019-01-06 03:32
@wajid23071dev
Postman does allow setting the payload (body) with requests having any method (including GET)
Please update to the latest version. This was released with version 6.5.0

**Comment by cedw032** [comment] 2019-02-01 13:50
I would prefer the freedom to send a body with get.  Not being able to do so is going to make my express code look gross. I'm writing my own API not using elasticsearch. +1 for elasticsearch

**Comment by numaanashraf** [comment] 2019-02-03 06:07
@cedw032 Could you elaborate better? Request body is not sent by default in GET requests, but you can choose to send it, if your API supports it.

**Comment by emilianito** [comment] 2019-03-09 14:11
+1 Elasticsearch

**Comment by JimLynchCodes** [comment] 2019-09-23 19:05
There is a "Body" option in Postman, but it becomes greyed out when you choose GET.

Postman devs... PLEASE CHANGE THIS!!

^ As you can see from all the above comments, ^ sending a body with a GET request is a perfectly valid thing to so it is absolutely silly and clearly a flagrant bug for this to not be available in Postman. SMH!

**Comment by JimLynchCodes** [comment] 2019-09-23 19:07
btw @harryi3t posted 1 year ago that this was in canary, but I just tried now and this feature is still not there... anyone know what's going on here?

**Comment by preethammavin** [comment] 2019-09-24 03:31
@JimTheMan can you let u know on what version of the app are you on currently, tried reproducing on Postman 7.7.3 but am able to send a get request with body.
