### ISSUE TITLE
Can't save key/value 'file' type on formdata , then app crashes

### ISSUE THREAD

**Issue by mshate123** [postmanlabs/postman-app-support#645] opened 2014-07-18 19:17 UTC
In the form-data section, I am trying to add a key/value pair of type 'file'. I choose file from the drop down and click 'save' to update the collection and nothing happens, no msg - no failure and also no success msg.
Then all other api collections fail, clicking 'send' highlights the button but nothing is sent. Verified this using charles proxy/wireshark, postman crashes. 
You have to restart the app.
I'm using : 
MacBook Pro
Software  OS X 10.9.4 (13E28)

**Comment by sofist-lucaskatayama** [comment] 2015-05-20 16:21
+1
Can't run Collection runner where one step is a fileupload....it fails

**Comment by abhijitkane** [comment] 2015-12-29 17:41
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/1113

**Closed by abhijitkane** 2015-12-29 17:41 UTC
Labels: Bug
