### ISSUE TITLE
Unchecked (Toggled Off) Header Still Sends in GET Request

### ISSUE THREAD

**Issue by rmdaustin** [postmanlabs/postman-app-support#846] opened 2014-12-12 00:41 UTC
In version 1.0.3 (packaged) I send a request with a header, then uncheck the header toggle, strike-through of header is shown, re-send the request and the header is still included.  Header is also visible in Preview.  Unless header is deleted, it always sends.  

Build:
![image](https://cloud.githubusercontent.com/assets/7613458/5405017/db015106-8164-11e4-855e-bb8cc7671c48.png)

Preview:
![image](https://cloud.githubusercontent.com/assets/7613458/5405030/0d1e3b9a-8165-11e4-8743-36ad121d7b32.png)

**Comment by abhijitkane** [comment] 2015-07-16 12:47
@rmdaustin Can you confirm this fixed in v3.0.4?

**Comment by bitdozer** [comment] 2015-07-16 12:59
It now works for one header per request.  But after toggling one, I can't toggle it back or toggle any other header until I submit the request.  

In this demonstration I click on Authorization, and then try clicking on it again, or any other header.  None of the clicks take effect.

https://www.dropbox.com/s/xeq0dw8dqdkkl4k/2015-07-16_7-53-59.mp4?dl=0

**Comment by abhijitkane** [comment] 2015-07-16 13:00
That's odd - can you check the console for any errors (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)?

**Comment by bitdozer** [comment] 2015-07-16 14:17
After doing that and restarting Postman I find that I cannot uncheck any header until after I run the request once.  Then I can uncheck one header, but must run the request to make any further header activations/deactivations.  Here's the log:

![postman-console-2015-07-16_9-14-23](https://cloud.githubusercontent.com/assets/7613458/8725713/6133971c-2b9b-11e5-9b1e-bee514b48029.jpg)

**Comment by abhijitkane** [comment] 2015-07-17 03:47
Right. We were able to reproduce this. Will push a fix in the next release.

**Comment by a85** [comment] 2015-09-05 21:02
Could not reproduce in the latest version of the app (3.0.13). Closing this.

**Closed by a85** 2015-09-05 21:02 UTC
Labels: Bug
