### ISSUE TITLE
Postman upload file crash

### ISSUE THREAD

**Issue by AdamJessop** [postmanlabs/postman-app-support#819] opened 2014-11-18 19:23 UTC
I have been working on an API which handles various audio formats however I have noticed that when trying to attach files to a POST request as form data, the application crashes if I select a .wav or .flac file (typically larger). I tested with a freely available FLAC file I found online:

http://thesixteendigital.com.s3.amazonaws.com/testfiles/Hallelujah.flac

As I state, the application is crashing as soon as I try and select the file using the 'Choose File' window, nothing to do with making an actual request.

Current version:

Version 1.0.1 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by a85** [comment] 2016-01-10 11:42
Closing this as a duplicate of #555. Will be tracked there.

**Closed by a85** 2016-01-10 11:42 UTC
Labels: Bug, Performance
