### ISSUE TITLE
Feature Request: Capture responses

### ISSUE THREAD

**Issue by rbecher** [postmanlabs/postman-app-support#906] opened 2015-02-05 07:38 UTC
I love the way I can send and filter requests from interceptor to (packaged) postman.

That way I can only see and inspect the requests (with the request data) though. This is OK for idempotent requests (HEAD, GET, OPTIONS), where I can simply click on "send" in postman. But it does not add much value for requests which are updating/creating/deleting data.

As a user I want to see the full response in addition to the request after having connected Postman with Interceptor for more insight into non-idempotent requests (typically create, update, delete). 

Additionally:
- I'd like to either have this as the default or a switch in the interceptor. 
- I can also think of using a simple proxy for this.
- In the long run I would love to use something like [membrane](http://www.membrane-soa.org/service-proxy/) for this

**Comment by prashantbhate** [comment] 2017-06-27 12:58
+1
This would be a very useful feature. 
With this on can add assertions/tests quickly before a re-running collection.

**Comment by a85** [comment] 2017-06-27 23:25
Closing as a duplicate of #622. Will track there.

**Closed by a85** 2017-06-27 23:25 UTC
Labels: Feature
