### ISSUE TITLE
Problems with navigation between postman app and chrome browser

### ISSUE THREAD

**Issue by sanofuzir** [postmanlabs/postman-app-support#770] opened 2014-10-23 23:19 UTC
If I open postman app and google chrome browser and when I want to changing between them It always open postman app but never browser. If I want to open the browser I must minimize the postman app to make it work. Is there any other way to navigate between this two?

**Comment by a85** [comment] 2015-07-17 22:07
Closing as duplicate of #1009. @msubel That's a great hack!

**Closed by a85** 2015-07-17 22:07 UTC
Labels: Bug

**Comment by a85** [comment] 2015-12-11 22:47
We have a Mac app out now people that solves these issues once and for all. Get it here: https://www.getpostman.com/apps

**Comment by mdellerie** [comment] 2016-04-25 14:49
@a85 thanks man 👍

**Comment by baelter** [comment] 2016-09-05 11:11
Sorry for bumping an old closed issue. But still can't tab between Chrome browser and Postman app. Even with the osx app.

**Comment by a85** [comment] 2016-09-07 20:52
@baelter Not sure what problem you are facing. Cmd+Tab is what you need to use with the OS X app. It's completely separate from the Chrome browser.

**Comment by baelter** [comment] 2016-09-08 08:31
Sorry, was using chrome app.

**Comment by gaoagong** [comment] 2016-11-07 17:38
I have a similar problem with a variation. I will open both chrome browser and PostMan, place them on different desktops of different monitors, and then when I try to use the key combo to switch between different windows of the same application (Cmd+Tab) it doesn't work. I have to go to the monitor and desktop with the chrome browser and then switch through the desktops to find it.

This is obviously a great annoyance.

Is this a mac problem, chrome problem, postman problem?
Any ideas on how to solve. 

I could do the same as above with creating 2 instances of Chrome, but I'd rather not if I don't have to.

**Comment by saurabhg476** [comment] 2016-12-28 05:44
On mac osx, `cmd + ~` works if all the windows of the same application are opened in the same workspace.
