### ISSUE TITLE
Postman breaks on long requests

### ISSUE THREAD

**Issue by slavafomin** [postmanlabs/postman-app-support#767] opened 2014-10-21 17:09 UTC
Hello and thanks for this great app, I love it!

However, I'm experiencing very annoying problem with *Postman*. Every time I do a "long" request that takes considerable amount of time (or even infinite length request) -- *Postman* hangs and is not responding. It doesn't help when I click a "cancel request" button or switch to another saved request. The only solution is to restart the app.

Could you fix this please?

Thanks!

**Comment by stevemcmillen** [comment] 2015-02-19 14:10
What happens when folks seeing unresponsive behavior if  you change the Postman response format to "RAW".  I have found that sometimes the long delays with large response sets is due to the parsing and prettifying of the response.

**Comment by robolivable** [comment] 2016-04-13 16:26
I'm seeing this happen with requests to bad URLs. For example, specifically to my use case, after changing the URL (and protocol to HTTPS) of my server, accidentally sending a request to the old URL hangs the application. The only fix is to restart Chrome as slavafomin mentioned above.

**Comment by boonep** [comment] 2016-04-18 14:40
Any update on this?  I am able to reproduce in Postman with Interceptor enabled:
1. Utilities -> Delay Response
      GET https://echo.getpostman.com/delay/10 (this appears to be maximum delay allowed)
2. Immediately Press "Cancel Request"
3. Utilities -> Response Status Code
      GET https://echo.getpostman.com/status/200
4.  Second request doesn't return until the first delay request is completed, despite the cancellation

Postman Interceptor 0.2.18
Postman 4.1.3
linux / x86-64
Chrome 49.0.2623.112

Thanks!

**Comment by abhijitkane** [comment] 2016-04-26 09:51
@robolivable What does the Network tab show (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)?

@boonep - This seems to be a separate issue. Your issue is due to the Interceptor being "single-threaded". We'll take this up sometime soon.

**Comment by numaanashraf** [comment] 2016-08-17 12:03
@madebysid @czardoz  can u verify and close if needed

**Comment by sdnts** [comment] 2016-09-12 09:44
Closing, as this is fixed as of the latest version (4.7)

**Closed by sdnts** 2016-09-12 09:44 UTC
Labels: Bug, Performance, runtime
