### ISSUE TITLE
Cmd-Tab to Chrome focuses Postman app

### ISSUE THREAD

**Issue by davidamitchell** [postmanlabs/postman-app-support#833] opened 2014-12-03 07:01 UTC
Firstly, thanks for making a packaged application, pretty awesome.

As mentioned here: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/zUS119qiowk

and:
<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/tumtumtum">@tumtumtum</a> <a href="https://twitter.com/postmanclient">@postmanclient</a> it is nice - just wish I could Cmd-Tab back to the Postman window though (OSX sees it as part of Chrome).</p>&mdash; Dan Herd (@DanHerd) <a href="https://twitter.com/DanHerd/status/418886421437767680">January 2, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Where as Postman is in the dock as its own application, and I can click on that dock icon and switch back and forth between Chrome and Postman, I cannot use Cmd-Tab to switch to Chrome from Postman or from anything else once Postman has had focus.

What I can do is:
* focus Postman
* use Cmd-Tab to go to any other app besides Chrome
* use Cmd-Tab to go choose Chrome (but see the Postman window)
* use Cmd-~ once to switch to the Chrome window

Other odd behavior:
* focus any application (say Terminal)
* focus Postman
* press Cmd-Tab once, I would expect to be have the Terminal application focused but instead Postman is still focused.

OSX: 10.9.5
Chrome: 39.0.2171.71 (64-bit)
Just installed the packaged app of Postman today.

Thanks

**Comment by joanrodriguez** [comment] 2015-03-17 18:00
Just switch between windows of the same app. http://superuser.com/questions/299241/in-mac-os-what-is-the-keyboard-shortcut-to-switch-between-windows-of-the-same-a

**Comment by velikanov** [comment] 2015-06-17 14:04
:+1: it horribly ruins all my life
my wife quit when she saw this behaviour
my cat doesn't eat the food that I give it
even my keyboard sometimes writes "i" instead of "I" you know
need help with this issue - it's really annoying

**Comment by velikanov** [comment] 2015-06-17 14:05
any way to set up postman as chrome tab instead of chrome app?

**Comment by a85** [comment] 2015-07-17 22:08
Closing this as duplicate of #1009

**Closed by a85** 2015-07-17 22:08 UTC
Labels: chrome-app-platform, Usability

**Comment by a85** [comment] 2015-12-11 22:47
We have a Mac app out now people that solves these issues once and for all. Get it here: https://www.getpostman.com/apps

**Comment by velikanov** [comment] 2015-12-12 12:53
@a85, the greatest news ever! thank you! :+1:

**Comment by crittelmeyer** [comment] 2016-01-01 19:47
:clap:

**Comment by acca** [comment] 2016-06-21 20:58
Thank you guys !

**Comment by gabel** [comment] 2016-07-19 15:44
👯  The world peace is possible again - thx for the dedicated app!
